# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Address(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, street_address: str=None, locality: str=None, region: str=None, postal_code: str=None, country: str=None):  # noqa: E501
        """Address - a model defined in Swagger

        :param street_address: The street_address of this Address.  # noqa: E501
        :type street_address: str
        :param locality: The locality of this Address.  # noqa: E501
        :type locality: str
        :param region: The region of this Address.  # noqa: E501
        :type region: str
        :param postal_code: The postal_code of this Address.  # noqa: E501
        :type postal_code: str
        :param country: The country of this Address.  # noqa: E501
        :type country: str
        """
        self.swagger_types = {
            'street_address': str,
            'locality': str,
            'region': str,
            'postal_code': str,
            'country': str
        }

        self.attribute_map = {
            'street_address': 'street_address',
            'locality': 'locality',
            'region': 'region',
            'postal_code': 'postal_code',
            'country': 'country'
        }

        self._street_address = street_address
        self._locality = locality
        self._region = region
        self._postal_code = postal_code
        self._country = country

    @classmethod
    def from_dict(cls, dikt) -> 'Address':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Address of this Address.  # noqa: E501
        :rtype: Address
        """
        return util.deserialize_model(dikt, cls)

    @property
    def street_address(self) -> str:
        """Gets the street_address of this Address.


        :return: The street_address of this Address.
        :rtype: str
        """
        return self._street_address

    @street_address.setter
    def street_address(self, street_address: str):
        """Sets the street_address of this Address.


        :param street_address: The street_address of this Address.
        :type street_address: str
        """

        self._street_address = street_address

    @property
    def locality(self) -> str:
        """Gets the locality of this Address.


        :return: The locality of this Address.
        :rtype: str
        """
        return self._locality

    @locality.setter
    def locality(self, locality: str):
        """Sets the locality of this Address.


        :param locality: The locality of this Address.
        :type locality: str
        """

        self._locality = locality

    @property
    def region(self) -> str:
        """Gets the region of this Address.


        :return: The region of this Address.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region: str):
        """Sets the region of this Address.


        :param region: The region of this Address.
        :type region: str
        """

        self._region = region

    @property
    def postal_code(self) -> str:
        """Gets the postal_code of this Address.


        :return: The postal_code of this Address.
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code: str):
        """Sets the postal_code of this Address.


        :param postal_code: The postal_code of this Address.
        :type postal_code: str
        """

        self._postal_code = postal_code

    @property
    def country(self) -> str:
        """Gets the country of this Address.


        :return: The country of this Address.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this Address.


        :param country: The country of this Address.
        :type country: str
        """

        self._country = country
