# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DomainRoleCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, domain_id: int=None, role_id: int=None, grant_implicitly: bool=None):  # noqa: E501
        """DomainRoleCreate - a model defined in Swagger

        :param domain_id: The domain_id of this DomainRoleCreate.  # noqa: E501
        :type domain_id: int
        :param role_id: The role_id of this DomainRoleCreate.  # noqa: E501
        :type role_id: int
        :param grant_implicitly: The grant_implicitly of this DomainRoleCreate.  # noqa: E501
        :type grant_implicitly: bool
        """
        self.swagger_types = {
            'domain_id': int,
            'role_id': int,
            'grant_implicitly': bool
        }

        self.attribute_map = {
            'domain_id': 'domain_id',
            'role_id': 'role_id',
            'grant_implicitly': 'grant_implicitly'
        }

        self._domain_id = domain_id
        self._role_id = role_id
        self._grant_implicitly = grant_implicitly

    @classmethod
    def from_dict(cls, dikt) -> 'DomainRoleCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_role_create of this DomainRoleCreate.  # noqa: E501
        :rtype: DomainRoleCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_id(self) -> int:
        """Gets the domain_id of this DomainRoleCreate.


        :return: The domain_id of this DomainRoleCreate.
        :rtype: int
        """
        return self._domain_id

    @domain_id.setter
    def domain_id(self, domain_id: int):
        """Sets the domain_id of this DomainRoleCreate.


        :param domain_id: The domain_id of this DomainRoleCreate.
        :type domain_id: int
        """
        if domain_id is None:
            raise ValueError("Invalid value for `domain_id`, must not be `None`")  # noqa: E501

        self._domain_id = domain_id

    @property
    def role_id(self) -> int:
        """Gets the role_id of this DomainRoleCreate.


        :return: The role_id of this DomainRoleCreate.
        :rtype: int
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id: int):
        """Sets the role_id of this DomainRoleCreate.


        :param role_id: The role_id of this DomainRoleCreate.
        :type role_id: int
        """
        if role_id is None:
            raise ValueError("Invalid value for `role_id`, must not be `None`")  # noqa: E501

        self._role_id = role_id

    @property
    def grant_implicitly(self) -> bool:
        """Gets the grant_implicitly of this DomainRoleCreate.


        :return: The grant_implicitly of this DomainRoleCreate.
        :rtype: bool
        """
        return self._grant_implicitly

    @grant_implicitly.setter
    def grant_implicitly(self, grant_implicitly: bool):
        """Sets the grant_implicitly of this DomainRoleCreate.


        :param grant_implicitly: The grant_implicitly of this DomainRoleCreate.
        :type grant_implicitly: bool
        """

        self._grant_implicitly = grant_implicitly
