# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DomainRoles(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, domain_id: int=None, roles_map: Dict[str, List[int]]=None):
        """
        DomainRoles - a model defined in Swagger

        :param domain_id: The domain_id of this DomainRoles.
        :type domain_id: int
        :param roles_map: The roles_map of this DomainRoles.
        :type roles_map: Dict[str, List[int]]
        """
        self.swagger_types = {
            'domain_id': int,
            'roles_map': Dict[str, List[int]]
        }

        self.attribute_map = {
            'domain_id': 'domain_id',
            'roles_map': 'roles_map'
        }

        self._domain_id = domain_id
        self._roles_map = roles_map

    @classmethod
    def from_dict(cls, dikt) -> 'DomainRoles':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_roles of this DomainRoles.
        :rtype: DomainRoles
        """
        return deserialize_model(dikt, cls)

    @property
    def domain_id(self) -> int:
        """
        Gets the domain_id of this DomainRoles.
        The domain for which the request was made.

        :return: The domain_id of this DomainRoles.
        :rtype: int
        """
        return self._domain_id

    @domain_id.setter
    def domain_id(self, domain_id: int):
        """
        Sets the domain_id of this DomainRoles.
        The domain for which the request was made.

        :param domain_id: The domain_id of this DomainRoles.
        :type domain_id: int
        """
        if domain_id is None:
            raise ValueError("Invalid value for `domain_id`, must not be `None`")

        self._domain_id = domain_id

    @property
    def roles_map(self) -> Dict[str, List[int]]:
        """
        Gets the roles_map of this DomainRoles.
        A dictionary where the keys are domain ids prefixed with `d:` and the values are lists of role ids.

        :return: The roles_map of this DomainRoles.
        :rtype: Dict[str, List[int]]
        """
        return self._roles_map

    @roles_map.setter
    def roles_map(self, roles_map: Dict[str, List[int]]):
        """
        Sets the roles_map of this DomainRoles.
        A dictionary where the keys are domain ids prefixed with `d:` and the values are lists of role ids.

        :param roles_map: The roles_map of this DomainRoles.
        :type roles_map: Dict[str, List[int]]
        """
        if roles_map is None:
            raise ValueError("Invalid value for `roles_map`, must not be `None`")

        self._roles_map = roles_map

