# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RoleResourcePermissionCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, role_id: int=None, resource_id: int=None, permission_id: int=None):  # noqa: E501
        """RoleResourcePermissionCreate - a model defined in Swagger

        :param role_id: The role_id of this RoleResourcePermissionCreate.  # noqa: E501
        :type role_id: int
        :param resource_id: The resource_id of this RoleResourcePermissionCreate.  # noqa: E501
        :type resource_id: int
        :param permission_id: The permission_id of this RoleResourcePermissionCreate.  # noqa: E501
        :type permission_id: int
        """
        self.swagger_types = {
            'role_id': int,
            'resource_id': int,
            'permission_id': int
        }

        self.attribute_map = {
            'role_id': 'role_id',
            'resource_id': 'resource_id',
            'permission_id': 'permission_id'
        }

        self._role_id = role_id
        self._resource_id = resource_id
        self._permission_id = permission_id

    @classmethod
    def from_dict(cls, dikt) -> 'RoleResourcePermissionCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The role_resource_permission_create of this RoleResourcePermissionCreate.  # noqa: E501
        :rtype: RoleResourcePermissionCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def role_id(self) -> int:
        """Gets the role_id of this RoleResourcePermissionCreate.


        :return: The role_id of this RoleResourcePermissionCreate.
        :rtype: int
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id: int):
        """Sets the role_id of this RoleResourcePermissionCreate.


        :param role_id: The role_id of this RoleResourcePermissionCreate.
        :type role_id: int
        """
        if role_id is None:
            raise ValueError("Invalid value for `role_id`, must not be `None`")  # noqa: E501

        self._role_id = role_id

    @property
    def resource_id(self) -> int:
        """Gets the resource_id of this RoleResourcePermissionCreate.


        :return: The resource_id of this RoleResourcePermissionCreate.
        :rtype: int
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id: int):
        """Sets the resource_id of this RoleResourcePermissionCreate.


        :param resource_id: The resource_id of this RoleResourcePermissionCreate.
        :type resource_id: int
        """
        if resource_id is None:
            raise ValueError("Invalid value for `resource_id`, must not be `None`")  # noqa: E501

        self._resource_id = resource_id

    @property
    def permission_id(self) -> int:
        """Gets the permission_id of this RoleResourcePermissionCreate.


        :return: The permission_id of this RoleResourcePermissionCreate.
        :rtype: int
        """
        return self._permission_id

    @permission_id.setter
    def permission_id(self, permission_id: int):
        """Sets the permission_id of this RoleResourcePermissionCreate.


        :param permission_id: The permission_id of this RoleResourcePermissionCreate.
        :type permission_id: int
        """
        if permission_id is None:
            raise ValueError("Invalid value for `permission_id`, must not be `None`")  # noqa: E501

        self._permission_id = permission_id
