# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class SiteRoleUpdate(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, grant_implicitly: bool=None):
        """
        SiteRoleUpdate - a model defined in Swagger

        :param grant_implicitly: The grant_implicitly of this SiteRoleUpdate.
        :type grant_implicitly: bool
        """
        self.swagger_types = {
            'grant_implicitly': bool
        }

        self.attribute_map = {
            'grant_implicitly': 'grant_implicitly'
        }

        self._grant_implicitly = grant_implicitly

    @classmethod
    def from_dict(cls, dikt) -> 'SiteRoleUpdate':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The site_role_update of this SiteRoleUpdate.
        :rtype: SiteRoleUpdate
        """
        return deserialize_model(dikt, cls)

    @property
    def grant_implicitly(self) -> bool:
        """
        Gets the grant_implicitly of this SiteRoleUpdate.

        :return: The grant_implicitly of this SiteRoleUpdate.
        :rtype: bool
        """
        return self._grant_implicitly

    @grant_implicitly.setter
    def grant_implicitly(self, grant_implicitly: bool):
        """
        Sets the grant_implicitly of this SiteRoleUpdate.

        :param grant_implicitly: The grant_implicitly of this SiteRoleUpdate.
        :type grant_implicitly: bool
        """

        self._grant_implicitly = grant_implicitly

