# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserDomainRoleCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: str=None, domain_id: int=None, role_id: int=None):  # noqa: E501
        """UserDomainRoleCreate - a model defined in Swagger

        :param user_id: The user_id of this UserDomainRoleCreate.  # noqa: E501
        :type user_id: str
        :param domain_id: The domain_id of this UserDomainRoleCreate.  # noqa: E501
        :type domain_id: int
        :param role_id: The role_id of this UserDomainRoleCreate.  # noqa: E501
        :type role_id: int
        """
        self.swagger_types = {
            'user_id': str,
            'domain_id': int,
            'role_id': int
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'domain_id': 'domain_id',
            'role_id': 'role_id'
        }

        self._user_id = user_id
        self._domain_id = domain_id
        self._role_id = role_id

    @classmethod
    def from_dict(cls, dikt) -> 'UserDomainRoleCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user_domain_role_create of this UserDomainRoleCreate.  # noqa: E501
        :rtype: UserDomainRoleCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this UserDomainRoleCreate.


        :return: The user_id of this UserDomainRoleCreate.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this UserDomainRoleCreate.


        :param user_id: The user_id of this UserDomainRoleCreate.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def domain_id(self) -> int:
        """Gets the domain_id of this UserDomainRoleCreate.


        :return: The domain_id of this UserDomainRoleCreate.
        :rtype: int
        """
        return self._domain_id

    @domain_id.setter
    def domain_id(self, domain_id: int):
        """Sets the domain_id of this UserDomainRoleCreate.


        :param domain_id: The domain_id of this UserDomainRoleCreate.
        :type domain_id: int
        """
        if domain_id is None:
            raise ValueError("Invalid value for `domain_id`, must not be `None`")  # noqa: E501

        self._domain_id = domain_id

    @property
    def role_id(self) -> int:
        """Gets the role_id of this UserDomainRoleCreate.


        :return: The role_id of this UserDomainRoleCreate.
        :rtype: int
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id: int):
        """Sets the role_id of this UserDomainRoleCreate.


        :param role_id: The role_id of this UserDomainRoleCreate.
        :type role_id: int
        """
        if role_id is None:
            raise ValueError("Invalid value for `role_id`, must not be `None`")  # noqa: E501

        self._role_id = role_id
