# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.role_label import RoleLabel  # noqa: F401,E501
from swagger_server import util


class UserSiteRoleLabelsAggregated(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: str=None, site_id: int=None, roles: List[RoleLabel]=None):  # noqa: E501
        """UserSiteRoleLabelsAggregated - a model defined in Swagger

        :param user_id: The user_id of this UserSiteRoleLabelsAggregated.  # noqa: E501
        :type user_id: str
        :param site_id: The site_id of this UserSiteRoleLabelsAggregated.  # noqa: E501
        :type site_id: int
        :param roles: The roles of this UserSiteRoleLabelsAggregated.  # noqa: E501
        :type roles: List[RoleLabel]
        """
        self.swagger_types = {
            'user_id': str,
            'site_id': int,
            'roles': List[RoleLabel]
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'site_id': 'site_id',
            'roles': 'roles'
        }

        self._user_id = user_id
        self._site_id = site_id
        self._roles = roles

    @classmethod
    def from_dict(cls, dikt) -> 'UserSiteRoleLabelsAggregated':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user_site_role_labels_aggregated of this UserSiteRoleLabelsAggregated.  # noqa: E501
        :rtype: UserSiteRoleLabelsAggregated
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this UserSiteRoleLabelsAggregated.


        :return: The user_id of this UserSiteRoleLabelsAggregated.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this UserSiteRoleLabelsAggregated.


        :param user_id: The user_id of this UserSiteRoleLabelsAggregated.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def site_id(self) -> int:
        """Gets the site_id of this UserSiteRoleLabelsAggregated.


        :return: The site_id of this UserSiteRoleLabelsAggregated.
        :rtype: int
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id: int):
        """Sets the site_id of this UserSiteRoleLabelsAggregated.


        :param site_id: The site_id of this UserSiteRoleLabelsAggregated.
        :type site_id: int
        """

        self._site_id = site_id

    @property
    def roles(self) -> List[RoleLabel]:
        """Gets the roles of this UserSiteRoleLabelsAggregated.


        :return: The roles of this UserSiteRoleLabelsAggregated.
        :rtype: List[RoleLabel]
        """
        return self._roles

    @roles.setter
    def roles(self, roles: List[RoleLabel]):
        """Sets the roles of this UserSiteRoleLabelsAggregated.


        :param roles: The roles of this UserSiteRoleLabelsAggregated.
        :type roles: List[RoleLabel]
        """

        self._roles = roles
