# coding: utf-8

# flake8: noqa
"""
    Authentication Service API

    This is the API that will be exposed by the Authentication Service. The Authentication Service facilitates user registration and login via web-based flows as defined for the OpenID Connect specification.   # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from authentication_service.models.client import Client
from authentication_service.models.user import User
from authentication_service.models.user_update import UserUpdate
