# coding: utf-8

"""
    Authentication Service API

    This is the API that will be exposed by the Authentication Service. The Authentication Service facilitates user registration and login via web-based flows as defined for the OpenID Connect specification.   # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UserUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'first_name': 'str',
        'last_name': 'str',
        'email': 'str',
        'is_active': 'bool',
        'email_verified': 'bool',
        'msisdn_verified': 'bool',
        'msisdn': 'str',
        'gender': 'str',
        'birth_date': 'date',
        'avatar': 'str',
        'country_code': 'str'
    }

    attribute_map = {
        'first_name': 'first_name',
        'last_name': 'last_name',
        'email': 'email',
        'is_active': 'is_active',
        'email_verified': 'email_verified',
        'msisdn_verified': 'msisdn_verified',
        'msisdn': 'msisdn',
        'gender': 'gender',
        'birth_date': 'birth_date',
        'avatar': 'avatar',
        'country_code': 'country_code'
    }

    def __init__(self, first_name=None, last_name=None, email=None, is_active=None, email_verified=None, msisdn_verified=None, msisdn=None, gender=None, birth_date=None, avatar=None, country_code=None):  # noqa: E501
        """UserUpdate - a model defined in Swagger"""  # noqa: E501

        self._first_name = None
        self._last_name = None
        self._email = None
        self._is_active = None
        self._email_verified = None
        self._msisdn_verified = None
        self._msisdn = None
        self._gender = None
        self._birth_date = None
        self._avatar = None
        self._country_code = None
        self.discriminator = None

        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if email is not None:
            self.email = email
        if is_active is not None:
            self.is_active = is_active
        if email_verified is not None:
            self.email_verified = email_verified
        if msisdn_verified is not None:
            self.msisdn_verified = msisdn_verified
        if msisdn is not None:
            self.msisdn = msisdn
        if gender is not None:
            self.gender = gender
        if birth_date is not None:
            self.birth_date = birth_date
        if avatar is not None:
            self.avatar = avatar
        if country_code is not None:
            self.country_code = country_code

    @property
    def first_name(self):
        """Gets the first_name of this UserUpdate.  # noqa: E501

          # noqa: E501

        :return: The first_name of this UserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UserUpdate.

          # noqa: E501

        :param first_name: The first_name of this UserUpdate.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this UserUpdate.  # noqa: E501

          # noqa: E501

        :return: The last_name of this UserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this UserUpdate.

          # noqa: E501

        :param last_name: The last_name of this UserUpdate.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this UserUpdate.  # noqa: E501

          # noqa: E501

        :return: The email of this UserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserUpdate.

          # noqa: E501

        :param email: The email of this UserUpdate.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def is_active(self):
        """Gets the is_active of this UserUpdate.  # noqa: E501

        Designates whether this user should be treated as active. Deselect this instead of deleting accounts.  # noqa: E501

        :return: The is_active of this UserUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this UserUpdate.

        Designates whether this user should be treated as active. Deselect this instead of deleting accounts.  # noqa: E501

        :param is_active: The is_active of this UserUpdate.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    @property
    def email_verified(self):
        """Gets the email_verified of this UserUpdate.  # noqa: E501


        :return: The email_verified of this UserUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._email_verified

    @email_verified.setter
    def email_verified(self, email_verified):
        """Sets the email_verified of this UserUpdate.


        :param email_verified: The email_verified of this UserUpdate.  # noqa: E501
        :type: bool
        """

        self._email_verified = email_verified

    @property
    def msisdn_verified(self):
        """Gets the msisdn_verified of this UserUpdate.  # noqa: E501


        :return: The msisdn_verified of this UserUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._msisdn_verified

    @msisdn_verified.setter
    def msisdn_verified(self, msisdn_verified):
        """Sets the msisdn_verified of this UserUpdate.


        :param msisdn_verified: The msisdn_verified of this UserUpdate.  # noqa: E501
        :type: bool
        """

        self._msisdn_verified = msisdn_verified

    @property
    def msisdn(self):
        """Gets the msisdn of this UserUpdate.  # noqa: E501


        :return: The msisdn of this UserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._msisdn

    @msisdn.setter
    def msisdn(self, msisdn):
        """Sets the msisdn of this UserUpdate.


        :param msisdn: The msisdn of this UserUpdate.  # noqa: E501
        :type: str
        """
        if msisdn is not None and len(msisdn) > 15:
            raise ValueError("Invalid value for `msisdn`, length must be less than or equal to `15`")  # noqa: E501

        self._msisdn = msisdn

    @property
    def gender(self):
        """Gets the gender of this UserUpdate.  # noqa: E501


        :return: The gender of this UserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender):
        """Sets the gender of this UserUpdate.


        :param gender: The gender of this UserUpdate.  # noqa: E501
        :type: str
        """

        self._gender = gender

    @property
    def birth_date(self):
        """Gets the birth_date of this UserUpdate.  # noqa: E501


        :return: The birth_date of this UserUpdate.  # noqa: E501
        :rtype: date
        """
        return self._birth_date

    @birth_date.setter
    def birth_date(self, birth_date):
        """Sets the birth_date of this UserUpdate.


        :param birth_date: The birth_date of this UserUpdate.  # noqa: E501
        :type: date
        """

        self._birth_date = birth_date

    @property
    def avatar(self):
        """Gets the avatar of this UserUpdate.  # noqa: E501


        :return: The avatar of this UserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this UserUpdate.


        :param avatar: The avatar of this UserUpdate.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def country_code(self):
        """Gets the country_code of this UserUpdate.  # noqa: E501


        :return: The country_code of this UserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this UserUpdate.


        :param country_code: The country_code of this UserUpdate.  # noqa: E501
        :type: str
        """
        if country_code is not None and len(country_code) > 2:
            raise ValueError("Invalid value for `country_code`, length must be less than or equal to `2`")  # noqa: E501

        self._country_code = country_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
