# coding: utf-8

"""
    Authentication Service API

    This is the API that will be exposed by the Authentication Service.  The Authentication Service facilitates user registration and login via web-based flows as defined for the OpenID Connect specification.   # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from authentication_service.api_client import ApiClient


class ExperimentalApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def authorize(self, client_id, response_type, scope, redirect_uri, state, **kwargs):  # noqa: E501
        """Authenticate a user  # noqa: E501

        Example: ``` GET https://localhost:8000/authorize?client_id=<your-client-id>&response_type=code+id_token&scope=openid+email&redirect_uri=<your-redirect-uri>&state=0123456789 ``` This endpoint is compatible with OpenID Connect and also supports the POST method, in which case the parameters are passed as a form post. See also:   - [OAuth 2.0 Authorization Endpoint](http://tools.ietf.org/html/rfc6749#section-3.1)   - [OIDC Authentication request](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)   - [OIDC Successful Authentication response](http://openid.net/specs/openid-connect-core-1_0.html#AuthResponse)   - [OIDC Error Authentication response](http://openid.net/specs/openid-connect-core-1_0.html#AuthError)   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.authorize(client_id, response_type, scope, redirect_uri, state, async=True)
        >>> result = thread.get()

        :param async bool
        :param str client_id: A client ID obtained from the [Dashboard](https://localhost:8000/admin/).  (required)
        :param str response_type: The OIDC response type to use for this authentication flow. Valid choices are `code`, `id_token`, `token`, `token id_token`, `code id_token` `code token` and `code token id_token`, but a client can be configured with a more restricted set.  (required)
        :param str scope: The space-separated identity claims to request from the end-user. Always include `openid` as a scope for compatibility with OIDC.  (required)
        :param str redirect_uri: The location to redirect to after (un)successful authentication. See OIDC for the parameters passed in the query string (`response_mode=query`) or as fragments (`response_mode=fragment`). This must be one of the registered redirect URLs.  (required)
        :param str state: An opaque string that will be passed back to the redirect URL and therefore can be used to communicate client side state and prevent CSRF attacks.  (required)
        :param str response_mode: Whether to append parameters to the redirect URL in the query string (`query`) or as fragments (`fragment`). This option usually has a sensible default for each of the response types. 
        :param str nonce: An nonce provided by the client that will be included in any ID Token generated for this session. Clients should use the nonce to mitigate replay attacks. 
        :param str display: The authentication display mode, which can be one of `page`, `popup` or `modal`. Defaults to `page`. 
        :param str prompt: Space-delimited, case sensitive list of ASCII string values that specifies whether the Authorization Server prompts the End-User for re-authentication and consent. The supported values are: `none`, `login`, `consent`. If `consent` the end-user is asked to (re)confirm what claims they share. Use `none` to check for an active session. 
        :param int max_age: Specifies the allowable elapsed time in seconds since the last time the end-user was actively authenticated. 
        :param str ui_locales: Specifies the preferred language to use on the authorization page, as a space-separated list of BCP47 language tags. Ignored at the moment. 
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.authorize_with_http_info(client_id, response_type, scope, redirect_uri, state, **kwargs)  # noqa: E501
        else:
            (data) = self.authorize_with_http_info(client_id, response_type, scope, redirect_uri, state, **kwargs)  # noqa: E501
            return data

    def authorize_with_http_info(self, client_id, response_type, scope, redirect_uri, state, **kwargs):  # noqa: E501
        """Authenticate a user  # noqa: E501

        Example: ``` GET https://localhost:8000/authorize?client_id=<your-client-id>&response_type=code+id_token&scope=openid+email&redirect_uri=<your-redirect-uri>&state=0123456789 ``` This endpoint is compatible with OpenID Connect and also supports the POST method, in which case the parameters are passed as a form post. See also:   - [OAuth 2.0 Authorization Endpoint](http://tools.ietf.org/html/rfc6749#section-3.1)   - [OIDC Authentication request](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)   - [OIDC Successful Authentication response](http://openid.net/specs/openid-connect-core-1_0.html#AuthResponse)   - [OIDC Error Authentication response](http://openid.net/specs/openid-connect-core-1_0.html#AuthError)   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.authorize_with_http_info(client_id, response_type, scope, redirect_uri, state, async=True)
        >>> result = thread.get()

        :param async bool
        :param str client_id: A client ID obtained from the [Dashboard](https://localhost:8000/admin/).  (required)
        :param str response_type: The OIDC response type to use for this authentication flow. Valid choices are `code`, `id_token`, `token`, `token id_token`, `code id_token` `code token` and `code token id_token`, but a client can be configured with a more restricted set.  (required)
        :param str scope: The space-separated identity claims to request from the end-user. Always include `openid` as a scope for compatibility with OIDC.  (required)
        :param str redirect_uri: The location to redirect to after (un)successful authentication. See OIDC for the parameters passed in the query string (`response_mode=query`) or as fragments (`response_mode=fragment`). This must be one of the registered redirect URLs.  (required)
        :param str state: An opaque string that will be passed back to the redirect URL and therefore can be used to communicate client side state and prevent CSRF attacks.  (required)
        :param str response_mode: Whether to append parameters to the redirect URL in the query string (`query`) or as fragments (`fragment`). This option usually has a sensible default for each of the response types. 
        :param str nonce: An nonce provided by the client that will be included in any ID Token generated for this session. Clients should use the nonce to mitigate replay attacks. 
        :param str display: The authentication display mode, which can be one of `page`, `popup` or `modal`. Defaults to `page`. 
        :param str prompt: Space-delimited, case sensitive list of ASCII string values that specifies whether the Authorization Server prompts the End-User for re-authentication and consent. The supported values are: `none`, `login`, `consent`. If `consent` the end-user is asked to (re)confirm what claims they share. Use `none` to check for an active session. 
        :param int max_age: Specifies the allowable elapsed time in seconds since the last time the end-user was actively authenticated. 
        :param str ui_locales: Specifies the preferred language to use on the authorization page, as a space-separated list of BCP47 language tags. Ignored at the moment. 
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['client_id', 'response_type', 'scope', 'redirect_uri', 'state', 'response_mode', 'nonce', 'display', 'prompt', 'max_age', 'ui_locales']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method authorize" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'client_id' is set
        if ('client_id' not in params or
                params['client_id'] is None):
            raise ValueError("Missing the required parameter `client_id` when calling `authorize`")  # noqa: E501
        # verify the required parameter 'response_type' is set
        if ('response_type' not in params or
                params['response_type'] is None):
            raise ValueError("Missing the required parameter `response_type` when calling `authorize`")  # noqa: E501
        # verify the required parameter 'scope' is set
        if ('scope' not in params or
                params['scope'] is None):
            raise ValueError("Missing the required parameter `scope` when calling `authorize`")  # noqa: E501
        # verify the required parameter 'redirect_uri' is set
        if ('redirect_uri' not in params or
                params['redirect_uri'] is None):
            raise ValueError("Missing the required parameter `redirect_uri` when calling `authorize`")  # noqa: E501
        # verify the required parameter 'state' is set
        if ('state' not in params or
                params['state'] is None):
            raise ValueError("Missing the required parameter `state` when calling `authorize`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'client_id' in params:
            query_params.append(('client_id', params['client_id']))  # noqa: E501
        if 'response_type' in params:
            query_params.append(('response_type', params['response_type']))  # noqa: E501
        if 'scope' in params:
            query_params.append(('scope', params['scope']))  # noqa: E501
        if 'redirect_uri' in params:
            query_params.append(('redirect_uri', params['redirect_uri']))  # noqa: E501
        if 'state' in params:
            query_params.append(('state', params['state']))  # noqa: E501
        if 'response_mode' in params:
            query_params.append(('response_mode', params['response_mode']))  # noqa: E501
        if 'nonce' in params:
            query_params.append(('nonce', params['nonce']))  # noqa: E501
        if 'display' in params:
            query_params.append(('display', params['display']))  # noqa: E501
        if 'prompt' in params:
            query_params.append(('prompt', params['prompt']))  # noqa: E501
        if 'max_age' in params:
            query_params.append(('max_age', params['max_age']))  # noqa: E501
        if 'ui_locales' in params:
            query_params.append(('ui_locales', params['ui_locales']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['APIKeyHeader']  # noqa: E501

        return self.api_client.call_api(
            '/openid/authorize', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def token(self, **kwargs):  # noqa: E501
        """Obtain an ID Token  # noqa: E501

        Exchange an authorization code for an ID Token or Access Token. This endpoint supports both `client_secret_post` and `client_secret_basic` authentication methods, as specified by the client's `token_endpoint_auth_method`. See also:   - [OIDC Token Endpoint](http://openid.net/specs/openid-connect-core-1_0.html#TokenRequest)   - [OIDC Successful Token response](http://openid.net/specs/openid-connect-core-1_0.html#TokenResponse)   - [OIDC Token Error response](http://openid.net/specs/openid-connect-core-1_0.html#TokenError)   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.token(async=True)
        >>> result = thread.get()

        :param async bool
        :param str authorization: HTTP Basic authorization header. 
        :param Content content:
        :return: Token
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.token_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.token_with_http_info(**kwargs)  # noqa: E501
            return data

    def token_with_http_info(self, **kwargs):  # noqa: E501
        """Obtain an ID Token  # noqa: E501

        Exchange an authorization code for an ID Token or Access Token. This endpoint supports both `client_secret_post` and `client_secret_basic` authentication methods, as specified by the client's `token_endpoint_auth_method`. See also:   - [OIDC Token Endpoint](http://openid.net/specs/openid-connect-core-1_0.html#TokenRequest)   - [OIDC Successful Token response](http://openid.net/specs/openid-connect-core-1_0.html#TokenResponse)   - [OIDC Token Error response](http://openid.net/specs/openid-connect-core-1_0.html#TokenError)   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.token_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str authorization: HTTP Basic authorization header. 
        :param Content content:
        :return: Token
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', 'content']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method token" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'content' in params:
            body_params = params['content']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIKeyHeader']  # noqa: E501

        return self.api_client.call_api(
            '/openid/token', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Token',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def user_info(self, **kwargs):  # noqa: E501
        """Retrieve their user profile  # noqa: E501

        Use this endpoint to retrieve a user's profile in case you've not already obtained enough details from the ID Token via the Token Endpoint.  See also:  - [OIDC UserInfo endpoint](http://openid.net/specs/openid-connect-core-1_0.html#UserInfo)   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.user_info(async=True)
        >>> result = thread.get()

        :param async bool
        :return: UserInfo
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.user_info_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.user_info_with_http_info(**kwargs)  # noqa: E501
            return data

    def user_info_with_http_info(self, **kwargs):  # noqa: E501
        """Retrieve their user profile  # noqa: E501

        Use this endpoint to retrieve a user's profile in case you've not already obtained enough details from the ID Token via the Token Endpoint.  See also:  - [OIDC UserInfo endpoint](http://openid.net/specs/openid-connect-core-1_0.html#UserInfo)   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.user_info_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :return: UserInfo
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method user_info" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth_code', 'oauth_implicit']  # noqa: E501

        return self.api_client.call_api(
            '/openid/userinfo', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='UserInfo',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
